name: showcase
version: 1.0
base: core

parts:
  mod1:
    plugin: python
    source: showcase
    source-branch: master
    source-subdir: mod1
  mod2:
    plugin: python
    source: showcase
    source-branch: master
    source-subdir: mod2
    after: [mod1]
