name: showcase
version: '1.0'
base: core
description: 'Showcase'
summary: 'Showcase'

parts:
  mod1:
    plugin: python
    source: .
    source-subdir: mod1
  mod2:
    plugin: python
    source: .
    source-subdir: mod2
    after: [mod1]
